---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deploy
  labels:
    app: bankfin-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankfin-app
  template:
    metadata:
      labels:
        app: bankfin-app
    spec:
      containers:
        - name: bankfin-app-container
          image: urvi11umesh/bankfin-app
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: bankfin-np-service
  labels:
    app: bankfin-app
spec:
  selector:
    app: bankfin-app
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31032  
